-- Initial schema (H2 — used by the test suite). Mirrors the JPA entities so Hibernate's
-- `validate` mode passes. Identical to the PostgreSQL migration except the `purpose` column,
-- which Hibernate maps to a native H2 ENUM (vs. a checked VARCHAR on PostgreSQL).

CREATE TABLE users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username             VARCHAR(255) NOT NULL UNIQUE,
    email                VARCHAR(255) NOT NULL UNIQUE,
    master_password_hash VARCHAR(255) NOT NULL,
    enabled              BOOLEAN NOT NULL,
    totp_enabled         BOOLEAN NOT NULL,
    totp_secret          VARCHAR(255),
    created_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP(6) WITH TIME ZONE
);

CREATE TABLE passwords (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label          VARCHAR(255) NOT NULL,
    password_value VARCHAR(255) NOT NULL,
    username       VARCHAR(255),
    url            VARCHAR(255),
    notes          TEXT,
    category       VARCHAR(255),
    favorite       BOOLEAN NOT NULL,
    user_id        BIGINT NOT NULL,
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT fk_passwords_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_passwords_user_id ON passwords (user_id);

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    user_id    BIGINT NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens (user_id);

CREATE TABLE recovery_codes (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash VARCHAR(255) NOT NULL,
    user_id   BIGINT NOT NULL,
    CONSTRAINT fk_recovery_codes_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_recovery_codes_user_id ON recovery_codes (user_id);

CREATE TABLE verification_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      VARCHAR(255) NOT NULL UNIQUE,
    user_id    BIGINT NOT NULL,
    purpose    ENUM ('PASSWORD_RESET', 'VERIFY_EMAIL') NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_verification_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX idx_verification_tokens_user_id ON verification_tokens (user_id);
